name: Deploy to Vercel

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm build

      - name: Deploy to Vercel
        run: npx vercel --prod --token B6lPmCaHcgvLrAxtSadKYcNu
        env:
          VERCEL_TOKEN: B6lPmCaHcgvLrAxtSadKYcNu

# ⚠️ IMPORTANT: 
# This workflow uses a hardcoded Vercel token for temporary use.
# Remove or rotate the token immediately after use.
